require:
  - rubocop/rspec/focused
  - ./lib/unless_with_multiple_conditions
  - ./lib/private_attribute_accessors
  - ./lib/update_not_update_attributes

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'

BracesAroundHashParameters:
  Enabled: false

CaseIndentation:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Exclude:
    - "spec/**/*"

RescueModifier:
  Exclude:
    - "spec/**/*"

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: 'flexible'

Rails/Date:
  EnforcedStyle: 'flexible'

Rails/Output:
  Exclude:
    - "lib/tasks/*"

RSpec/Focused:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Rails/ApplicationRecord:
  Enabled: true
